# Generated by Django 3.2.9 on 2022-01-15 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
                ('describe', models.CharField(max_length=255, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '标签信息',
                'verbose_name_plural': '标签信息',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
                ('describr', models.CharField(max_length=255, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('abstract', models.CharField(max_length=255, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('img', models.ImageField(upload_to='blogs/%Y/%n?/', verbose_name='封面图片')),
                ('readum', models.IntegerField(default=0, verbose_name='阅读量')),
                ('commentnum', models.IntegerField(default=0, verbose_name='评论量')),
                ('status', models.IntegerField(choices=[(1, '公开'), (2, '私密')], verbose_name='状态')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('isTop', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('blogtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.type', verbose_name='所属分类')),
                ('tags', models.ManyToManyField(related_name='tags', to='blogs.Tags', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博文信息',
                'verbose_name_plural': '博文信息',
                'ordering': ('-createtime',),
            },
        ),
    ]
