# Generated by Django 3.2.9 on 2022-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_describr_type_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(upload_to='blogs/%Y/', verbose_name='封面图片'),
        ),
    ]
