# Generated by Django 3.2.9 on 2022-01-15 17:00

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='readum',
            new_name='readnum',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
