# Generated by Django 3.2.9 on 2022-01-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20220115_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('-isTop', '-createtime'), 'verbose_name': '博文信息', 'verbose_name_plural': '博文信息'},
        ),
    ]
